const ITEMS_DATA = [
    { id: "item_1", name: "Держатель для стакана, 2 шт", points: 250, completed: false },
    { id: "item_2", name: "Духи мужские стойкие Блю седактон Blue seduction 10 мл", points: 250, completed: false },
    { id: "item_3", name: "Антенна для SMA мужской 868 МГц 5,8 дБи", points: 250, completed: false },
    { id: "item_4", name: "Адаптер для шланга", points: 250, completed: false },
    { id: "item_5", name: "Топ красный", points: 250, completed: false },
    { id: "item_6", name: "Топ черный", points: 250, completed: false },
    { id: "item_7", name: "Топ белый", points: 250, completed: false },
    { id: "item_8", name: "Измеритель зазора свечи зажигания 0.6-2.4 мм", points: 250, completed: false },
    { id: "item_9", name: "Блеск для губ QIBEST34 цветной матовый", points: 250, completed: false },
    { id: "item_10", name: "Губная грязь DIXI матовая бархатная", points: 250, completed: false },
    { id: "item_11", name: "Очки солнцезащитные оранжевые", points: 200, completed: false },
    { id: "item_12", name: "Очки солнцезащитные чёрные", points: 200, completed: false },
    { id: "item_13", name: "Очки солнцезащитные белые", points: 200, completed: false },
    { id: "item_14", name: "Очки солнцезащитные жёлтые", points: 200, completed: false },
    { id: "item_15", name: "Ароматизатор автомобильный синий колокольчик", points: 250, completed: false },
    { id: "item_16", name: "Ароматизатор автомобильный, роза", points: 250, completed: false },
    { id: "item_17", name: "Мелки для волос", points: 200, completed: false },
    { id: "item_18", name: "Искусственные цветы, 1шт", points: 250, completed: false },
    { id: "item_19", name: "Сумка складная хозяйственная", points: 200, completed: false },
    { id: "item_20", name: "Косметичка дорожная", points: 250, completed: false },
    { id: "item_21", name: "Сумка саквояж", points: 250, completed: false },
    { id: "item_22", name: "Сумка для ручной клади", points: 250, completed: false },
    { id: "item_23", name: "Помада-карандаш матовая 18 цветов розовый", points: 250, completed: false },
    { id: "item_24", name: "Помада-карандаш матовая 18 цветов красный", points: 250, completed: false },
    { id: "item_25", name: "Карандаш для губ матовый набор 12 оттенков VIOLET", points: 250, completed: false },
    { id: "item_26", name: "Пояс", points: 250, completed: false },
    { id: "item_27", name: "Чехол для Realme 5i полностью закрытый силиконовый", points: 250, completed: false },
    { id: "item_28", name: "Серьги зеленые", points: 250, completed: false },
    { id: "item_29", name: "Серьги голубые с красным", points: 250, completed: false }
    { id: "item_30", name: "Серьги голубые", points: 250, completed: false }
];
export default ITEMS_DATA;
